version: '3.3'


services:
  db:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./
      dockerfile: ./
    env_file: ./.env
    depends_on:
      - db